#!/bin/tcsh
#PBS -N usgsV
#PBS -l nodes=1:vortex:ppn=12
#PBS -l walltime=00:01:00
#PBS -j oe


# init conda within new shell for job
source "/usr/local/anaconda3-2021.05/etc/profile.d/conda.csh"
module load anaconda3/2021.05
module load openmpi/3.1.4/gcc-9.3.0
unsetenv PYTHONPATH
conda activate dhsrl4

cd geo

python train.py